= Supernaut.FX Sample Gradle Build

image:https://github.com/SupernautApp/supernautfx-sample-gradle/workflows/Gradle%20Build/badge.svg["Build Status", link="https://github.com/SupernautApp/supernautfx-sample-gradle/actions"]


== Overview

This project contains a sample, "Hello World"-style https://github.com/SupernautApp/SupernautFX[Supernaut.FX] application using built with https://gradle.org[Gradle], the https://badass-jlink-plugin.beryx.org/releases/latest/[Badass JLink Plugin], https://docs.oracle.com/javase/9/tools/jlink.htm[jlink] and https://docs.oracle.com/en/java/javase/17/docs/specs/man/jpackage.html[jpackage] to produce natively-packaged applications for Linux, macOS, and Windows.

== Setup

. Install JDK 17 or later.

== Build Instructions

. `git clone git@github.com:SupernautApp/supernaut-fx-sample-gradle.git`
. `cd supernaut-fx-sample-gradle`
. `./gradlew build`

To run via Gradle:

* `./gradlew run`

To build a natively-packaged executable:

* `./gradlew jpackageImage`

The executable can be found in the `build/jpackage` directory.

To build a native package for distribution:

* `./gradlew jpackage`

The installer package can be found in the `build/jpackage` directory.

== Building with GraalVM and Gluon

=== Setup

. Install Graal VM `java17` version 22.0.0.2 or later (Latest GraalVM JDK 17)
. Set `GRAALVM_HOME` environment variable

If you are building a GraalVM native image with GluonFX you may need to install additional software (depending upon your platform) see the https://docs.gluonhq.com/[Gluon Documentation] for info.

=== Building a Native Image

To build:

* `./gradlew nativeBuild`

to run:

* `./gradlew nativeBuild nativeRun`

or to build a package:

* `./gradlew nativeBuild nativePackage`

The native packages can then be found in: `./build/gluonfx/<platform>/`


