name: Gradle Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: ['17-ea']
        distribution: ['zulu']
      fail-fast: false
    name: ${{ matrix.os }} JDK ${{ matrix.distribution }} ${{ matrix.java }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Set up JDK
      id: setupjdk
      uses: actions/setup-java@v2.2.0
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
    - name: Verify Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Build with Gradle
      run: ./gradlew build jpackage --scan --info --stacktrace
    - name: Upload DMG as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: supernaut-fx-gradle-sample-${{ matrix.os }}-jdk${{ matrix.java }}-dmg
        path: build/jpackage/*.dmg
        if-no-files-found: ignore
    - name: Upload EXE as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: supernaut-fx-gradle-sample-${{ matrix.os }}-jdk${{ matrix.java }}-exe
        path: build/jpackage/*.exe
        if-no-files-found: ignore
    - name: Upload DEB as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: supernaut-fx-gradle-sample-${{ matrix.os }}-jdk${{ matrix.java }}-deb
        path: build/jpackage/*.deb
        if-no-files-found: ignore
    - name: Upload RPM as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: supernaut-fx-gradle-sample-${{ matrix.os }}-jdk${{ matrix.java }}-rpm
        path: build/jpackage/*.rpm
        if-no-files-found: ignore
